project:
  type: website
  output-dir: docs

website:
  title: "Jaccottet Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Corpus OCR
      - href: regex.qmd
        text: Regex
      - href: frequency.qmd
        text: Frequency
      - href: cooc.qmd
        text: Coocurence

format:
  html:
    theme:
      - slate
    css: styles.css
    toc: true

editor: visual

